config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :beams do
    member do
      get "like", to: "beams#upvote"
      get "dislike", to: "beams#downvote"
    end
    resources :comments
  end
  root 'beams#index'
end

app/models/beam.rb
class Beam < ActiveRecord::Base
  acts_as_votable
  belongs_to :user
  has_many :comments
  has_attached_file :image, styles: { large: "3584x1792>", small: "500x250>" }
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :beam
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :beams
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :name
    devise_parameter_sanitizer.for(:account_update) << :name
  end
end

app/controllers/beams_controller.rb
class BeamsController < ApplicationController
  before_action :find_beam, only: [:show, :edit, :update, :destroy, :upvote, :downvote]
  before_action :authenticate_user!, except: [:index, :show] 
  def index
    @beams = Beam.all.order("created_at DESC")
  end
  
  def show
    @comments = Comment.where(beam_id: @beam)
  end
  
  def new
    @beam = current_user.beams.build
  end
  
  def create
    @beam = current_user.beams.build(beam_params)
    
    if @beam.save
      redirect_to @beam
    else
      render 'new'
    end
  end
  
  def edit
    
  end
  
  def update
    if @beam.update(beam_params)
      redirect_to @beam
    else
      render 'edit'
    end
  end
  
  def destroy
    @beam.destroy
    redirect_to root_path
  end
  
  def upvote
    @beam.upvote_by current_user
    redirect_to :back
  end
  
  def downvote
    @beam.downvote_by current_user
    redirect_to :back
  end
  
  private
  
  def find_beam
       @beam = Beam.find(params[:id])
  end
  
  def beam_params
    params.require(:beam).permit(:title, :description, :image)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user! 
  def create
    @beam = Beam.find(params[:beam_id])
    @comment = Comment.create(params[:comment].permit(:content))
    @comment.user_id = current_user.id
    @comment.beam_id = @beam.id
    
    if @comment.save
      redirect_to beam_path(@beam)
    else
      render 'new'
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/beams_helper.rb
module BeamsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/beams/_form.html.haml
= simple_form_for @beam do |f|
  
  .form-group
    = f.input :image, input_html: {class: 'form-control'}
    = f.input :title, input_html: {class: 'form-control'}
    = f.input :description, input_html: {class: 'form-control'}

  = f.button :submit, class: "btn btn-primary"
  

app/views/beams/_jumbotron.html.haml
.jumbotron
  %center
    = image_tag("logo2.png")
    %h2 The worlds easiest immersive storytelling tool
    = link_to "New Beam", new_beam_path, class: "btn-lg btn-success"
    %P hold the card to your andorid phone and see the  story

app/views/beams/edit.html.haml
.col-md-6.col-md-offset-3
  %h1 Edit Beams 
  = image_tag @beam.image.url(:small)
  = render 'form'

app/views/beams/index.html.haml
= render 'jumbotron'

.container
  - @beams.each do |beam|
    = link_to (image_tag beam.image.url(:small)) , beam
    %h2= link_to beam.title, beam
    %p
      = beam.comments.count
      Comments
    %p
      = beam.get_likes.size
  
= link_to "Add new Beam", new_beam_path

app/views/beams/new.html.haml
.col-md-6.col-md-offset-3
  .rom
    .panel.panel-default
      .panel-heading
        %h1 Add New Beams
      .panel-body
        = render 'form'

app/views/beams/show.html.haml
.conatiner
  = image_tag @beam.image.url(:large)
  %h1= @beam.title
  %p= @beam.description
  Submitted by
  %p= @beam.user.name
  %p
  = @beam.get_upvotes.size
  Likes
  %p
  = @beam.get_downvotes.size
  Disklikes
  = link_to "Like", like_beam_path(@beam), method: :get
  = link_to "Dislike", dislike_beam_path(@beam), method: :get

  #comment
    %h2.comment_count= pluralize(@beam.comments.count, "Comment")
    - @comments.each do |comment|
      .comment
        %p.username= comment.user.name
        %p.content= comment.content
      
    = render 'comments/form'
  
  
  = link_to "Edit", edit_beam_path(@beam)
  = link_to "Destroy", beam_path(@beam), method: :delete, data: { confirm: "Are you sure?"}
  = link_to "Home", root_path

app/views/comments/_form.html.haml
= simple_form_for([@beam, @beam.comments.build]) do |f|
  = f.input :content, label: "Reply to thread"
  = f.button :submit, class: "button"

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Seebeam
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    %nav.navbar-fixed-top.navbar-default
      .container
        .navbar-brand= link_to image_tag("logo.png"), root_path
        
        - if user_signed_in?
          %ul.nav.navbar-nav.navbar-right
            %li= link_to "New Beam", new_beam_path
            %li= link_to "Account", edit_user_registration_path
            %li= link_to "Sign Out", destroy_user_session_path, method: :delete
        - else
          %ul.nav.navbar-nav.navbar-right
            %li= link_to "Sign Up", new_user_registration_path
            %li= link_to "Sign In", new_user_session_path
  
    %p.notice= notice
    %p.alert= alert

    = yield